// hostel: {
//     type: String,
//     enum: [
//       "Lagos Boys Hostel",
//       "Lagos Girls Hostel",
//       "Pyramid Hostel",
//       "Sky Hostel",
//       "Takleemah Hostel",
//       "Health care Hostel",
//       "Cooperative Hostel",
//       "Sanusi Hostel",
//       "Arafims 1 Hostel",
//       "Arafims 2 Hostel",
//       "Hawa Hostel",
//       "Kikelomo Hostel",
//       "Ibidun Hostel",
//       "Atlantic Heights Hostel",
//       "Trunil Hostel",
//       "Charis hostel",
//       "Needs Hostel",
//       "Al-mutawakil Hostel",
//       "Abuja Girls Hostel",
//       "ASUU Hostel",
//       "Unilorin Probitas Hostel",
//       "Micheal Hostel",
//       "Easy and Quiet Hostel",
//       "Zamfara Hostel",
//       "Kam Abioye Hostel",
//       "Moremi Hostel",
//       "Albanic Hostel",
//       "Robiat Ajike Hostel",
//       "Primerose Hostel",
//       "Habeebah Abake Hostel",
//       "Queens Hostel",
//       "Gulf Pearl Hostel",
//       "El-Mubarak Hostel",
//       "Scientific Hostel",
//       "Bethany Hostel",
//       "Zapel Hostel",
//       "Rubik’s Hostel",
//       "International Hostel",
//       "Sasakawa/Peacesetter Hostel",
//       "Edge hostel",
//       "Easy and Quiet 2(college)",
//       "Al-Noor Hostel (college)",
//       "School hostel (college)",
//     ],
//     // required: true,
//   },


// FirstName: { type: String, required: true },
// LastName: { type: String, required: true },

// department: {
//     type: String,
//     enum: [
//       "Computer Science",
//       "Maths",
//       "Biology",
//       "Chemistry",
//       "Zoology",
//       "Fishery",
//     ],
//     // required: true,
//   },
